//  TopSales
export const LOAD_TOPSALES_FAILURE = "LOAD_TOPSALES_FAILURE";
export const LOAD_TOPSALES_REQUEST = "LOAD_TOPSALES_REQUEST";
export const LOAD_TOPSALES_SUCCESS = "LOAD_TOPSALES_SUCCESS";
// Categories
export const LOAD_CATEGORIES_FAILURE = "LOAD_CATEGORIES_FAILURE";
export const LOAD_CATEGORIES_REQUEST = "LOAD_CATEGORIES_REQUEST";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const RESET_CATEGORY = "RESET_CATEGORY";
//Products
export const LOAD_PRODUCTS_FAILURE = "LOAD_PRODUCTS_FAILURE";
export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const UPDATE_SEARCH_STRING = "UPDATE_SEARCH_STRING";
export const SET_NAVIGATE_FROM_HEADER = "SET_NAVIGATE_FROM_HEADER";
//  ProductItem
export const LOAD_PRODUCTITEM_FAILURE = "LOAD_PRODUCTITEM_FAILURE";
export const LOAD_PRODUCTITEM_REQUEST = "LOAD_PRODUCTITEM_REQUEST";
export const LOAD_PRODUCTITEM_SUCCESS = "LOAD_PRODUCTITEM_SUCCESS";
