//  TopSales
export const LOAD_TOPSALES_FAILURE = "LOAD_TOPSALES_FAILURE";
export const LOAD_TOPSALES_REQUEST = "LOAD_TOPSALES_REQUEST";
export const LOAD_TOPSALES_SUCCESS = "LOAD_TOPSALES_SUCCESS";
// Categories
export const LOAD_CATEGORIES_FAILURE = "LOAD_CATEGORIES_FAILURE";
export const LOAD_CATEGORIES_REQUEST = "LOAD_CATEGORIES_REQUEST";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const RESET_CATEGORY = "RESET_CATEGORY";
//Products
export const LOAD_PRODUCTS_FAILURE = "LOAD_PRODUCTS_FAILURE";
export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const UPDATE_SEARCH_STRING = "UPDATE_SEARCH_STRING";
export const SET_NAVIGATE_FROM_HEADER = "SET_NAVIGATE_FROM_HEADER";
//  ProductItem
export const LOAD_PRODUCTITEM_FAILURE = "LOAD_PRODUCTITEM_FAILURE";
export const LOAD_PRODUCTITEM_REQUEST = "LOAD_PRODUCTITEM_REQUEST";
export const LOAD_PRODUCTITEM_SUCCESS = "LOAD_PRODUCTITEM_SUCCESS";
//  Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const RESTORE_CART_FROM_STORAGE = "RESTORE_CART_FROM_STORAGE";
//  Order
export const SEND_ORDER_REQUEST = "SEND_ORDER_REQUEST";
export const SEND_ORDER_SUCCESS = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_FAILURE = "SEND_ORDER_FAILURE";
export const RESET_ORDER = "RESET_ORDER";
